#!/usr/bin/env python3
"""
Generate all publication and presentation plots.

Outputs to plots/ (project root):
  entropy_pesq_scatter.png      Main paper finding: entropy vs PESQ across phases
  phase_progression.png         PESQ + STOI across the 8-phase curriculum
  dim_entropy_heatmap.png       Per-dimension entropy heatmap (32 dims x 6 phases)
  ood_bitrate.png               OOD signal types vs effective bitrate
  speaker_probe_recall.png      Per-speaker recall from linear probe
  corruption_robustness.png     Decompression success rate vs bit error rate

The R-D curve is generated by scripts/13_rd_sweep.py and saved separately.
"""

import sys
from pathlib import Path

import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

# ---------------------------------------------------------------------------
# Data (all real numbers from 2026-07-01 Windows evaluation)
# ---------------------------------------------------------------------------

PHASES = ['C', 'D', 'D-VAE', 'E', 'F', 'G']

PHASE_DATA = {
    'C':     {'kbps': 5.7,  'pesq': 1.202, 'stoi': 0.733, 'entropy': 1.462, 'comp_ratio': 1.657},
    'D':     {'kbps': 5.8,  'pesq': 1.222, 'stoi': 0.731, 'entropy': 1.455, 'comp_ratio': 1.650},
    'D-VAE': {'kbps': 4.6,  'pesq': 1.181, 'stoi': 0.702, 'entropy': 1.090, 'comp_ratio': 2.145},
    'E':     {'kbps': 5.9,  'pesq': 1.262, 'stoi': 0.751, 'entropy': 1.533, 'comp_ratio': 1.593},
    'F':     {'kbps': 5.9,  'pesq': 1.265, 'stoi': 0.766, 'entropy': 1.521, 'comp_ratio': 1.612},
    'G':     {'kbps': 5.9,  'pesq': 1.279, 'stoi': 0.766, 'entropy': 1.520, 'comp_ratio': 1.609},
}

# Source: comparisons/2026-06-30_compression_analysis/report.txt
DIM_ENTROPY = {
    'C':     [1.563,1.510,1.264,1.286,1.559,1.531,1.684,1.736,1.561,1.604,1.449,1.385,
              1.499,1.307,1.498,1.390,1.422,1.515,1.527,1.600,1.402,1.519,1.581,1.286,
              1.539,1.531,1.333,1.426,1.514,0.988,1.358,1.416],
    'D':     [1.502,1.514,1.261,1.301,1.540,1.571,1.644,1.664,1.570,1.594,1.467,1.416,
              1.413,1.343,1.497,1.379,1.422,1.549,1.527,1.560,1.392,1.520,1.573,1.298,
              1.495,1.526,1.282,1.398,1.507,1.050,1.361,1.419],
    'D-VAE': [1.215,1.099,0.894,0.969,1.201,1.218,1.338,1.271,1.190,1.178,1.072,1.007,
              1.123,0.955,1.073,1.032,1.147,1.120,1.211,1.184,1.030,1.039,1.280,0.869,
              1.249,1.097,1.006,1.047,1.146,0.654,0.906,1.071],
    'E':     [1.606,1.615,1.271,1.282,1.598,1.517,1.789,1.824,1.639,1.672,1.553,1.437,
              1.607,1.410,1.602,1.503,1.454,1.573,1.608,1.734,1.575,1.560,1.704,1.346,
              1.672,1.552,1.509,1.518,1.538,0.970,1.408,1.401],
    'F':     [1.543,1.589,1.265,1.282,1.613,1.515,1.785,1.829,1.637,1.649,1.544,1.418,
              1.555,1.421,1.583,1.465,1.450,1.559,1.585,1.691,1.551,1.547,1.719,1.338,
              1.681,1.563,1.469,1.482,1.542,1.011,1.408,1.391],
    'G':     [1.527,1.594,1.257,1.271,1.593,1.510,1.803,1.828,1.642,1.644,1.547,1.421,
              1.558,1.429,1.591,1.485,1.430,1.551,1.578,1.709,1.548,1.544,1.729,1.345,
              1.674,1.557,1.461,1.480,1.541,1.015,1.401,1.388],
}

OOD_DATA = [
    ('Sine 440 Hz',          0.34,  -0.004, False),
    ('Speech + reverb',      1.29,   0.272, True),
    ('Freq sweep 200-4k Hz', 3.72,   0.193, False),
    ('Pink noise (1/f)',      8.30,   0.439, False),
    ('White noise',          7.65,   0.410, False),
    ('Speech + 0 dB noise',  7.20,   0.563, True),
    ('Clean speech (ref)',   5.97,   0.760, True),
]

SPEAKER_RECALL = sorted([
    ('1089', 12.5), ('1188', 75.0), ('1221', 37.5), ('1284',  0.0),
    ('1320', 37.5), ('1580', 50.0), ('1995', 50.0), ('2094', 62.5),
    ('2300', 12.5), ('260',  25.0), ('2830', 25.0), ('2961', 12.5),
    ('3575', 12.5), ('3729', 50.0), ('4077', 50.0), ('4446', 62.5),
    ('4507', 12.5), ('5105', 12.5), ('5142', 12.5), ('5639', 50.0),
    ('672',  12.5), ('6829', 50.0), ('6930',100.0), ('7021', 12.5),
    ('7127', 37.5), ('7176', 50.0), ('7729', 12.5), ('8224', 50.0),
    ('8230', 50.0), ('8455', 75.0), ('8463', 25.0), ('908',  12.5),
], key=lambda x: x[1])


# ---------------------------------------------------------------------------
# Plot helpers
# ---------------------------------------------------------------------------

BLUE    = '#2878b5'
ORANGE  = '#e07b39'
CRIMSON = '#c0392b'
GRAY    = '#7f8c8d'
GREEN   = '#27ae60'

def _save(fig, path, dpi=150):
    fig.savefig(path, dpi=dpi, bbox_inches='tight')
    import matplotlib.pyplot as plt
    plt.close(fig)
    print(f"  saved: {path.name}")


# ---------------------------------------------------------------------------
# 1. Entropy-PESQ scatter (main paper figure)
# ---------------------------------------------------------------------------

def plot_entropy_pesq_scatter(out_dir):
    import matplotlib.pyplot as plt

    fig, ax = plt.subplots(figsize=(7, 5))

    marker_style = {'C': 'o', 'D': 's', 'D-VAE': 'D', 'E': '^', 'F': 'v', 'G': '*'}
    label_offset = {
        'C':     ( 6,  4),
        'D':     ( 6, -12),
        'D-VAE': (-72,  4),
        'E':     ( 6,  4),
        'F':     ( 6, -12),
        'G':     ( 6,  4),
    }

    # Dashed trend line through non-VAE phases
    non_vae = [p for p in PHASES if p != 'D-VAE']
    ax.plot(
        [PHASE_DATA[p]['entropy'] for p in non_vae],
        [PHASE_DATA[p]['pesq']   for p in non_vae],
        '--', color=BLUE, alpha=0.25, linewidth=1.5, zorder=2,
    )

    for phase in PHASES:
        d = PHASE_DATA[phase]
        is_vae = phase == 'D-VAE'
        color  = CRIMSON if is_vae else BLUE
        size   = 200 if phase == 'G' else (180 if is_vae else 100)
        ax.scatter(
            d['entropy'], d['pesq'],
            c=color, marker=marker_style[phase],
            s=size, zorder=5, edgecolors='white', linewidths=0.6,
        )
        ax.annotate(
            f'Phase {phase}',
            (d['entropy'], d['pesq']),
            textcoords='offset points',
            xytext=label_offset[phase],
            fontsize=9,
            color=CRIMSON if is_vae else BLUE,
            fontweight='bold' if phase in ('G', 'D-VAE') else 'normal',
        )

    ax.set_xlabel('Mean latent entropy per dimension H(d)  (bits)', fontsize=11)
    ax.set_ylabel('PESQ-WB', fontsize=11)
    ax.set_title('Entropy–Quality Tension Across Training Phases',
                 fontsize=12, fontweight='bold')
    ax.grid(True, alpha=0.25)

    ax.text(0.03, 0.97,
            'more compressible  ←',
            transform=ax.transAxes, fontsize=8, color=GRAY,
            va='top', ha='left', style='italic')
    ax.text(0.97, 0.97,
            '→  higher quality',
            transform=ax.transAxes, fontsize=8, color=GRAY,
            va='top', ha='right', style='italic')

    from matplotlib.lines import Line2D
    legend_elements = [
        Line2D([0],[0], marker='o', color='w', markerfacecolor=BLUE,
               markersize=8, label='Training phases (C, D, E, F, G)'),
        Line2D([0],[0], marker='D', color='w', markerfacecolor=CRIMSON,
               markersize=8, label='Phase D-VAE  (KL regularisation)'),
    ]
    ax.legend(handles=legend_elements, fontsize=9, loc='lower right')

    _save(fig, out_dir / 'entropy_pesq_scatter.png')


# ---------------------------------------------------------------------------
# 2. Phase progression bar chart
# ---------------------------------------------------------------------------

def plot_phase_progression(out_dir):
    import matplotlib.pyplot as plt

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 5), sharey=False)
    fig.suptitle('Quality Metrics Across the 8-Phase Training Curriculum',
                 fontsize=12, fontweight='bold')

    x     = np.arange(len(PHASES))
    width = 0.55
    pesqs = [PHASE_DATA[p]['pesq'] for p in PHASES]
    stois = [PHASE_DATA[p]['stoi'] for p in PHASES]
    colors = [CRIMSON if p == 'D-VAE' else BLUE for p in PHASES]

    # PESQ subplot
    bars1 = ax1.bar(x, pesqs, width, color=colors, alpha=0.85,
                    edgecolor='white', linewidth=0.5)
    for bar, v in zip(bars1, pesqs):
        ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.001,
                 f'{v:.3f}', ha='center', va='bottom', fontsize=8.5, color='#333')
    ax1.set_xticks(x)
    ax1.set_xticklabels([f'Phase {p}' for p in PHASES], fontsize=9.5)
    ax1.set_ylabel('PESQ-WB', fontsize=11)
    ax1.set_ylim(1.14, 1.31)
    ax1.grid(True, axis='y', alpha=0.25)
    ax1.spines['top'].set_visible(False)
    ax1.spines['right'].set_visible(False)
    ax1.annotate('KL forces\nquality down', xy=(2, 1.181), xytext=(2, 1.155),
                 ha='center', fontsize=8, color=CRIMSON,
                 arrowprops=dict(arrowstyle='->', color=CRIMSON, lw=1.2))

    # STOI subplot
    colors_stoi = [CRIMSON if p == 'D-VAE' else ORANGE for p in PHASES]
    bars2 = ax2.bar(x, stois, width, color=colors_stoi, alpha=0.85,
                    edgecolor='white', linewidth=0.5)
    for bar, v in zip(bars2, stois):
        ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.001,
                 f'{v:.3f}', ha='center', va='bottom', fontsize=8.5, color='#333')
    ax2.set_xticks(x)
    ax2.set_xticklabels([f'Phase {p}' for p in PHASES], fontsize=9.5)
    ax2.set_ylabel('STOI', fontsize=11)
    ax2.set_ylim(0.67, 0.79)
    ax2.grid(True, axis='y', alpha=0.25)
    ax2.spines['top'].set_visible(False)
    ax2.spines['right'].set_visible(False)
    ax2.annotate('KL forces\nquality down', xy=(2, 0.702), xytext=(2, 0.674),
                 ha='center', fontsize=8, color=CRIMSON,
                 arrowprops=dict(arrowstyle='->', color=CRIMSON, lw=1.2))

    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor=BLUE,    label='Phase (PESQ)'),
        Patch(facecolor=ORANGE,  label='Phase (STOI)'),
        Patch(facecolor=CRIMSON, label='Phase D-VAE — KL regularisation'),
    ]
    fig.legend(handles=legend_elements, fontsize=9, loc='lower center',
               ncol=3, bbox_to_anchor=(0.5, -0.03))

    plt.tight_layout(rect=[0, 0.06, 1, 1])
    _save(fig, out_dir / 'phase_progression.png')


# ---------------------------------------------------------------------------
# 3. Per-dimension entropy heatmap
# ---------------------------------------------------------------------------

def plot_dim_entropy_heatmap(out_dir):
    import matplotlib.pyplot as plt

    data = np.array([DIM_ENTROPY[p] for p in PHASES])   # (6, 32)

    fig, ax = plt.subplots(figsize=(14, 4))
    im = ax.imshow(data, aspect='auto', cmap='YlOrRd', vmin=0.6, vmax=1.9)

    ax.set_yticks(range(len(PHASES)))
    ax.set_yticklabels([f'Phase {p}' for p in PHASES], fontsize=10)
    ax.set_xticks(range(32))
    ax.set_xticklabels([str(i) for i in range(32)], fontsize=7)
    ax.set_xlabel('Latent dimension index', fontsize=11)
    ax.set_title('Shannon Entropy per Latent Dimension (bits)  —  max = 3.0 bits',
                 fontsize=12, fontweight='bold')

    cbar = fig.colorbar(im, ax=ax, fraction=0.015, pad=0.01)
    cbar.set_label('Entropy (bits)', fontsize=9)

    # Annotate dim 29 (the consistently weakest dimension)
    ax.annotate('dim 29\n(weakest)', xy=(29, 0), xytext=(26, -0.8),
                textcoords='data',
                arrowprops=dict(arrowstyle='->', color='black', lw=1.0),
                fontsize=8, color='black')

    # Horizontal separator to highlight D-VAE row
    ax.axhline(y=1.5, color='white', linewidth=2)
    ax.axhline(y=2.5, color='white', linewidth=2)

    plt.tight_layout()
    _save(fig, out_dir / 'dim_entropy_heatmap.png')


# ---------------------------------------------------------------------------
# 4. OOD bitrate chart
# ---------------------------------------------------------------------------

def plot_ood_bitrate(out_dir):
    import matplotlib.pyplot as plt

    labels = [d[0] for d in OOD_DATA]
    kbps   = [d[1] for d in OOD_DATA]
    stois  = [d[2] for d in OOD_DATA]
    is_sp  = [d[3] for d in OOD_DATA]

    colors = [BLUE if sp else ORANGE for sp in is_sp]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4.5))

    # Left: bitrate
    bars = ax1.barh(labels, kbps, color=colors, alpha=0.85,
                    edgecolor='white', linewidth=0.5)
    ax1.axvline(x=9.6, color='gray', linestyle='--', linewidth=1.2, label='9.6 kbps cap')
    for bar, v in zip(bars, kbps):
        ax1.text(bar.get_width() + 0.1, bar.get_y() + bar.get_height()/2,
                 f'{v:.2f}', va='center', ha='left', fontsize=8.5)
    ax1.set_xlabel('Effective bitrate (kbps)', fontsize=11)
    ax1.set_title('Bitrate tracks signal complexity', fontsize=11, fontweight='bold')
    ax1.set_xlim(0, 10.5)
    ax1.legend(fontsize=8)
    ax1.grid(True, axis='x', alpha=0.25)
    ax1.spines['top'].set_visible(False)
    ax1.spines['right'].set_visible(False)

    # Right: STOI
    bars2 = ax2.barh(labels, stois, color=colors, alpha=0.85,
                     edgecolor='white', linewidth=0.5)
    for bar, v in zip(bars2, stois):
        xpos = max(bar.get_width(), 0) + 0.01
        ax2.text(xpos, bar.get_y() + bar.get_height()/2,
                 f'{v:.3f}', va='center', ha='left', fontsize=8.5)
    ax2.set_xlabel('STOI', fontsize=11)
    ax2.set_title('Intelligibility by signal type', fontsize=11, fontweight='bold')
    ax2.set_xlim(-0.1, 1.0)
    ax2.axvline(x=0.0, color='gray', linestyle='-', linewidth=0.5)
    ax2.grid(True, axis='x', alpha=0.25)
    ax2.spines['top'].set_visible(False)
    ax2.spines['right'].set_visible(False)

    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor=BLUE,   label='Speech signal'),
        Patch(facecolor=ORANGE, label='Synthetic signal'),
    ]
    fig.legend(handles=legend_elements, fontsize=9, loc='lower center',
               ncol=2, bbox_to_anchor=(0.5, -0.02))

    fig.suptitle('Out-of-Distribution Evaluation — Phase G', fontsize=12, fontweight='bold')
    plt.tight_layout(rect=[0, 0.05, 1, 1])
    _save(fig, out_dir / 'ood_bitrate.png')


# ---------------------------------------------------------------------------
# 5. Speaker identity probe recall
# ---------------------------------------------------------------------------

def plot_speaker_probe_recall(out_dir):
    import matplotlib.pyplot as plt

    speakers = [s[0] for s in SPEAKER_RECALL]
    recalls  = [s[1] for s in SPEAKER_RECALL]
    mean_acc = 35.8
    chance   = 3.125  # 1/32

    colors = [CRIMSON if r == 0.0 else (GREEN if r == 100.0 else BLUE) for r in recalls]

    fig, ax = plt.subplots(figsize=(10, 6))
    bars = ax.barh(speakers, recalls, color=colors, alpha=0.85,
                   edgecolor='white', linewidth=0.5)

    ax.axvline(x=chance,   color='gray',   linestyle='--', linewidth=1.2,
               label=f'Chance ({chance:.1f}%)')
    ax.axvline(x=mean_acc, color=ORANGE,   linestyle='-',  linewidth=1.5,
               label=f'Mean accuracy ({mean_acc:.1f}%)')

    for bar, v in zip(bars, recalls):
        ax.text(bar.get_width() + 0.5, bar.get_y() + bar.get_height()/2,
                f'{v:.0f}%', va='center', ha='left', fontsize=8)

    ax.set_xlabel('Recall (%)', fontsize=11)
    ax.set_ylabel('Speaker ID', fontsize=11)
    ax.set_title('Speaker Identity Linear Probe — Per-Speaker Recall\n'
                 '(32 speakers, 3s clips, frozen Phase G encoder, 32-dim mean-pooled latent)',
                 fontsize=11, fontweight='bold')
    ax.set_xlim(0, 115)
    ax.grid(True, axis='x', alpha=0.25)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.legend(fontsize=9, loc='lower right')

    from matplotlib.patches import Patch
    extra = [
        Patch(facecolor=GREEN,  label='100% recall (perfectly separable)'),
        Patch(facecolor=BLUE,   label='Partial recall'),
        Patch(facecolor=CRIMSON, label='0% recall (confused with others)'),
    ]
    ax.legend(handles=extra + ax.get_legend_handles_labels()[0][2:],
              fontsize=8, loc='lower right')

    plt.tight_layout()
    _save(fig, out_dir / 'speaker_probe_recall.png')


# ---------------------------------------------------------------------------
# 6. Corruption robustness
# ---------------------------------------------------------------------------

def plot_corruption_robustness(out_dir):
    import matplotlib.pyplot as plt

    # Use log-scale positions so low BER points don't crowd together.
    # 0% BER is shown separately at a fixed left position.
    bers_nonzero = [0.001, 0.005, 0.010, 0.020, 0.050, 0.100]
    success_nonzero = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    fig, ax = plt.subplots(figsize=(8, 4.5))

    # Plot non-zero BER points on a log x-axis
    ax.set_xscale('log')
    ax.step([0.0009] + bers_nonzero, [100.0] + success_nonzero, where='post',
            color=BLUE, linewidth=2.5, label='zlib decompression success')
    ax.fill_between([0.0009] + bers_nonzero, [100.0] + success_nonzero, step='post',
                    color=BLUE, alpha=0.15)
    ax.scatter([0.001] + bers_nonzero[1:], success_nonzero, color=BLUE, s=60, zorder=5)
    # Mark the 0% BER point separately
    ax.scatter([0.0009], [100.0], color=GREEN, s=80, zorder=6)
    ax.annotate('0% BER\n100% success', xy=(0.0009, 100), xytext=(0.0013, 80),
                fontsize=8, color=GREEN,
                arrowprops=dict(arrowstyle='->', color=GREEN, lw=1.0))

    ax.axvline(x=0.001, color=CRIMSON, linestyle='--', linewidth=1.2,
               label='0.1% BER → 0% success')

    ax.set_xlabel('Bit error rate (log scale)', fontsize=11)
    ax.set_ylabel('Decompression success rate (%)', fontsize=11)
    ax.set_title('Bitstream Corruption Robustness\n'
                 '(zlib CRC-32: binary failure — perfect or total)',
                 fontsize=11, fontweight='bold')
    ax.set_ylim(-5, 115)
    ax.set_xlim(0.0007, 0.15)
    ax.set_xticks(bers_nonzero)
    ax.set_xticklabels(['0.1%', '0.5%', '1.0%', '2.0%', '5.0%', '10.0%'], fontsize=9)
    ax.grid(True, alpha=0.25, which='both')
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.legend(fontsize=9, loc='center right')

    ax.text(0.012, 50,
            'Channel coding layer\n(e.g., Reed-Solomon)\nrequired for deployment',
            ha='center', va='center', fontsize=9, color=GRAY,
            bbox=dict(boxstyle='round,pad=0.4', facecolor='lightyellow',
                      edgecolor=GRAY, alpha=0.8))

    plt.tight_layout()
    _save(fig, out_dir / 'corruption_robustness.png')


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    try:
        import matplotlib
        matplotlib.use('Agg')
        import matplotlib.pyplot as plt
    except ImportError:
        print("ERROR: matplotlib not available. Install it with: pip install matplotlib")
        return

    out_dir = PROJECT_ROOT / 'plots'
    out_dir.mkdir(exist_ok=True)

    print(f"\nGenerating plots → {out_dir}/\n")

    plot_entropy_pesq_scatter(out_dir)
    plot_phase_progression(out_dir)
    plot_dim_entropy_heatmap(out_dir)
    plot_ood_bitrate(out_dir)
    plot_speaker_probe_recall(out_dir)
    plot_corruption_robustness(out_dir)

    print(f"\nDone. {len(list(out_dir.glob('*.png')))} plots in {out_dir}/")
    print("R-D curve: comparisons/2026-07-01_rd_sweep/rd_curve.png (generated separately)")


if __name__ == '__main__':
    main()
